# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - cmake
    - pkg-config
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r docs/requirements.txt
      - pip install -e .

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .