# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - build-essential
    - cmake
    - pkg-config
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      # - pip install --ignore-installed docutils==0.17.1
      - pip install -r docs/requirements.txt
      # - pip install torch torchvision torchaudio
      #- pip install torch==1.10.0+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      # - pip install -e . --no-deps
      - conda install -y spacy
      - python -m spacy download fr_core_news_lg
      - python -m spacy download en_core_web_lg
      - conda install -y -c dglteam/label/th24_cpu dgl
      # - conda install -c dglteam dgl


sphinx:
  configuration: docs/conf.py

# python:
#   install:
#     - requirements: docs/requirements.txt

conda:
  environment: environment.yml
