# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
      extra_requirements:
        - docs
    - method: pip
      path: .
      extra_requirements:
        - docs

# Additional configurations
build:
  apt_packages:
    - build-essential
    - cmake
    - pkg-config

# Custom commands
commands:
  pre_install:
    - pip install --upgrade pip setuptools wheel
    - pip install torch==1.10.0+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html