# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - cmake
    - pkg-config
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install torch==1.10.0+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - pip install --ignore-installed docutils==0.17.1
      - pip install -r docs/requirements.txt
      - pip install -e . --no-deps

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs