# .readthedocs.yaml

version: 2



# 构建文档的配置
build:
  image: "ubuntu-22.04"  # 选择使用的操作系统镜像
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  requirements:
    files:
      - requirements.txt
  install:
    - pip install --no-deps SocialED==1.1.2
# Sphinx 配置
sphinx:
  configuration: docs/conf.py
