# .readthedocs.yaml

version: 2



# 构建文档的配置
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Python 配置
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

# Sphinx 配置
sphinx:
  configuration: docs/conf.py
