version: 2

# 构建环境设置
build:
  os: "ubuntu-22.04"  # 设置操作系统为 ubuntu-22.04
  tools:
    python: "3.8"  # 设置 Python 版本为 3.8

# 使用 requirements.txt 文件安装依赖
requirements:
  file: requirements.txt  # 使用 requirements.txt 安装依赖

# 构建文档
sphinx:
  configuration: docs/conf.py  # 指定 Sphinx 配置文件的位置
