name: socialed
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  # Core dependencies
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cpuonly
  
  # Scientific computing
  - numpy
  - pandas
  - scikit-learn
  - scipy
  
  # Graph related
  - networkx
  
  # NLP tools
  - spacy
  - gensim
  
  # Testing
  - pytest
  - pytest-cov
  - coverage
  
  - pip:
    # Transformers ecosystem
    - transformers==4.27.4
    - tokenizers==0.13.3
    - accelerate==0.18.0
    - sentence-transformers==2.2.2
    
    # Graph related
    - torch-geometric==2.3.0
    - dgl
    - faiss-cpu
    
    # Other dependencies
    - pytorch-ignite==0.4.11
    - geoopt==0.4.0
    - coveralls
    - GitPython
    - matplotlib
    - seaborn
    
    # Language models
    - en-core-web-lg
    - fr-core-news-lg

