name: socialed
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pyg
  - faiss-cpu
  - pip:
    - transformers==4.30.2
    - tokenizers==0.13.3
    - accelerate==0.20.3
    - sentence-transformers==2.2.2
    - peft==0.3.0
    - geoopt==0.5.0
    - pytorch-ignite==0.5.0.post2
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - pytest
    - pytest-cov
    - coverage
    - coveralls
    - GitPython
    - gensim

