name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # 安装 PyTorch 相关依赖
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        conda install pyg -c pyg
        conda install -c conda-forge faiss-cpu
        
        # 安装 transformers 相关依赖
        conda install -c conda-forge tokenizers transformers
        
        # 安装其他依赖
        python -m pip install --upgrade pip
        pip install pylint autopep8
        pip install -r requirements.txt

    - name: Run Pylint
      shell: bash -l {0}
      run: |
        # 创建输出目录
        mkdir -p pylint_output
        
        # 运行 pylint 并保存输出
        pylint --rcfile=.pylintrc SocialED > pylint_output/report.txt || true
        
        # 提取分数
        if grep -q "Your code has been rated at" pylint_output/report.txt; then
          score=$(grep "Your code has been rated at" pylint_output/report.txt | awk '{print $7}' | cut -d'/' -f1)
        else
          score="0"
        fi
        
        # 显示报告
        cat pylint_output/report.txt
        
        # 如果分数低于 2.0，运行 autopep8
        if (( $(echo "$score < 2.0" | bc -l) )); then
          echo "Pylint score ($score) is less than 2.0. Running autopep8..."
          find SocialED -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
          pylint --rcfile=.pylintrc SocialED > pylint_output/final_report.txt
          cat pylint_output/final_report.txt
        fi
        
        # 最终检查
        pylint --rcfile=.pylintrc SocialED --fail-under=2.0
