name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        pip install -r requirements.txt

    - name: Initial Pylint Check
      id: pylint-check
      run: |
        pylint SocialED || true

    - name: Check Pylint Score
      id: score-check
      run: |
        score=$(pylint SocialED | tee /dev/tty | grep 'Your code has been rated at' | awk '{print $7}' | cut -d/ -f1)
        echo "score=$score" >> $GITHUB_OUTPUT

    - name: Conditional Autopep8 Fix and Recheck
      if: steps.score-check.outputs.score < 2.0
      run: |
        echo "Pylint score (${{ steps.score-check.outputs.score }}) is less than 2.0. Running autopep8..."
        find SocialED -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
        pylint SocialED

    - name: Final Pylint Check
      if: steps.score-check.outputs.score < 2.0
      run: |
        pylint SocialED --fail-under=2.0
