name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Install PyTorch dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        conda install pyg -c pyg
        conda install -c conda-forge faiss-cpu

    - name: Install other dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        pip install -r requirements.txt

    - name: Initial Pylint Check
      shell: bash -l {0}
      id: pylint-check
      run: |
        pylint --rcfile=.pylintrc SocialED || true

    - name: Check Pylint Score
      shell: bash -l {0}
      id: score-check
      run: |
        score=$(pylint --rcfile=.pylintrc SocialED | tee /dev/tty | grep 'Your code has been rated at' | awk '{print $7}' | cut -d/ -f1)
        echo "score=$score" >> $GITHUB_OUTPUT

    - name: Conditional Autopep8 Fix and Recheck
      if: steps.score-check.outputs.score < 2.0
      shell: bash -l {0}
      run: |
        echo "Pylint score (${{ steps.score-check.outputs.score }}) is less than 2.0. Running autopep8..."
        find SocialED -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
        pylint --rcfile=.pylintrc SocialED

    - name: Final Pylint Check
      if: steps.score-check.outputs.score < 2.0
      shell: bash -l {0}
      run: |
        pylint --rcfile=.pylintrc SocialED --fail-under=2.0
