name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Create Pylint config
      shell: bash -l {0}
      run: |
        pylint --generate-rcfile > .pylintrc

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # 安装 PyTorch 相关依赖
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        conda install pyg -c pyg
        conda install -c conda-forge faiss-cpu
        
        # 安装 transformers 相关依赖
        conda install -c conda-forge tokenizers transformers
        
        # 安装其他依赖
        python -m pip install --upgrade pip
        pip install pylint autopep8
        pip install -r requirements.txt

    - name: Run Pylint
      shell: bash -l {0}
      run: |
        # 运行 pylint 检查
        pylint SocialED || echo "Pylint check completed with warnings"
