name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Install initial tools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8

    - name: Create Pylint config
      shell: bash -l {0}
      run: |
        pylint --generate-rcfile > .pylintrc

    - name: Install PyTorch dependencies
      shell: bash -l {0}
      run: |
        # Install specific PyTorch version
        conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch
        conda install pyg==2.3.0 -c pyg
        conda install -c conda-forge faiss-cpu==1.7.2

    - name: Install transformers dependencies
      shell: bash -l {0}
      run: |
        pip install transformers==4.27.4 \
                    tokenizers==0.13.3 \
                    accelerate==0.18.0 \
                    sentence-transformers==2.2.2

    - name: Install scientific computing dependencies
      shell: bash -l {0}
      run: |
        conda install numpy==1.24.4 \
                      pandas==2.0.3 \
                      scikit-learn==1.3.2 \
                      scipy==1.10.1 \
                      networkx==3.1 \
                      matplotlib==3.7.5 \
                      seaborn

    - name: Install NLP dependencies
      shell: bash -l {0}
      run: |
        pip install spacy==3.7.4 \
                    gensim==4.3.2
        python -m spacy download en_core_web_lg
        python -m spacy download fr_core_news_lg

    - name: Install other dependencies
      shell: bash -l {0}
      run: |
        pip install dgl==0.6.0 \
                    pytorch-ignite==0.4.11

    - name: Run Pylint
      shell: bash -l {0}
      run: |
        # Run pylint check
        pylint SocialED || echo "Pylint check completed with warnings"
