name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        auto-update-conda: true

    - name: Install test dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest