name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict
        
    - name: Install initial tools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov GitPython gensim

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Install PyTorch related dependencies
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        conda install pyg -c pyg
        conda install -c conda-forge faiss-cpu
        
        # Install transformers related dependencies
        conda install -c conda-forge tokenizers transformers
        
        # Install other dependencies
        pip install -r requirements.txt

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest