name: Read the Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Install documentation tools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme sphinx-gallery
        pip install sphinxcontrib-bibtex
        pip install recommonmark

    - name: Install PyTorch dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch=1.13.1 torchvision=0.14.1 torchaudio=0.13.1 cpuonly -c pytorch
        conda install pyg -c pyg
        conda install -c conda-forge faiss-cpu

    - name: Install scientific computing dependencies
      shell: bash -l {0}
      run: |
        conda install numpy pandas scikit-learn scipy networkx matplotlib seaborn -c conda-forge

    - name: Install NLP dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge spacy gensim
        python -m spacy download en_core_web_lg
        python -m spacy download fr_core_news_lg

    - name: Install transformers dependencies
      shell: bash -l {0}
      run: |
        pip install transformers==4.27.4
        pip install tokenizers==0.13.3
        pip install accelerate==0.18.0
        pip install sentence-transformers==2.2.2

    - name: Install other dependencies
      shell: bash -l {0}
      run: |
        pip install dgl pytorch-ignite

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make html

    - name: Trigger Read the Docs build
      run: |
        curl -X POST -d "" https://readthedocs.org/api/v3/projects/socialed/builds/ \
        -H "Authorization: Token ${{ secrets.RTD_TOKEN }}"
      env:
        RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
