name: Read the Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: socialed
        python-version: ${{ matrix.python-version }}
        channels: pytorch,conda-forge,defaults
        channel-priority: strict

    - name: Install documentation tools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install sphinx==7.1.2
        pip install sphinx-rtd-theme==1.3.0
        pip install sphinx-gallery==0.15.0
        pip install sphinxcontrib-bibtex==2.6.1
        pip install recommonmark==0.7.1

    - name: Install core dependencies
      shell: bash -l {0}
      run: |
        # Install numpy first
        pip install numpy==1.24.4
        
        # Install PyTorch CPU version
        pip install torch==1.13.1+cpu torchvision==0.14.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
        
        # Install other core dependencies
        pip install pandas==2.0.3 \
                    scikit-learn==1.3.2 \
                    scipy==1.10.1 \
                    networkx==3.1 \
                    matplotlib==3.7.5

    - name: Install NLP dependencies
      shell: bash -l {0}
      run: |
        pip install spacy==3.5.3
        pip install gensim==4.3.2
        python -m spacy download en_core_web_sm
        python -m spacy download fr_core_news_sm

    - name: Install transformers dependencies
      shell: bash -l {0}
      run: |
        pip install transformers==4.27.4 \
                    tokenizers==0.13.3 \
                    accelerate==0.18.0 \
                    sentence-transformers==2.2.2

    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make html

    - name: Trigger Read the Docs build
      run: |
        curl -X POST -d "" https://readthedocs.org/api/v3/projects/socialed/builds/ \
        -H "Authorization: Token ${{ secrets.RTD_TOKEN }}"
      env:
        RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
